### ISSUE TITLE
in rails 3, 'rake db:schema:dump' does not dump the view

### ISSUE THREAD

**Issue by flavorjones** [activewarehouse/rails_sql_views#5]
using rails 3.0.0, mysql 2.8.1, rails_sql_views 0.8.0

the view was created via a migration (using create_view) and works fine. but db/schema.rb does not contain the view schema, even after an explicit 'rake db:schema:dump'

**Comment by rgabo** [comment]
+1, pull request included in #6, fork available at sspinc/rails_sql_views until pulled

tx

**Comment by flavorjones** [comment]
+1 on @rgabo's pull request, which solves the issue for me.
